[www]
; Melhorando Pool Otimizado
; O default do PHP-FPM alpino é minúsculo (geralmente dynamic, 5 min, 2 spare)
; Isso causa esgotamento do server ('server reached pm.max_children') rapidamente.

pm = dynamic
pm.max_children = 40
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 15

; Limite de solicitações antes de reiniciar o processo (ajuda no memory leak em dev local longo)
pm.max_requests = 1000

; Evitando timeout no request (match com Nginx fastcgi_read_timeout)
request_terminate_timeout = 300

; Idle FPM 
pm.process_idle_timeout = 30s
