[PHP]
memory_limit = 512M
max_execution_time = 120
post_max_size = 128M
upload_max_filesize = 128M
variables_order = "EGPCS"
date.timezone = America/Sao_Paulo

; Desativar output warnings nativos pro Laravel gerenciar The Whoops
display_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

; Otimização crítica de I/O em Windows Bind-mount e Autoloads do Composer
realpath_cache_size=4096K
realpath_cache_ttl=600

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=32
opcache.max_accelerated_files=32531

; Como estamos rodando as regras em runtime pelo Docker no Windows e pode haver delay
; Optei por ligar validação de timestamp. Para ambiente de PURA produção e zero delays, 
; isso deve ser `0` e limparemos reconstruindo o container.
opcache.validate_timestamps=1
opcache.revalidate_freq=0
opcache.save_comments=1
opcache.fast_shutdown=1
